In [21]:
#Q1 abc_numpy solution
#Create a numpy array of strings containing letters 'a' through 'j' (inclusive) of the alphabet. Then, use numpy array attributes to print the following information about this array:

#dtype of array

#shape of array
#size of array

#The code you submit in the code editor below will not be graded. Use the results from your code below, along with what you remember from the previous video, to complete the quiz below the code editor.



import numpy as np

# create numpy array of letters a-j
letter_array = np.array(['a', 'b', 'c', 'd', 'e', 'g', 'h', 'i', 'j'])
print("Letter Array: ", letter_array)

# get dtype of array
print('dtype of array:',type(letter_array))

# get shape of array
print('shape of array:',letter_array.shape)

# get size of array
print('size of array:',letter_array.size)

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'g' 'h' 'i' 'j']
dtype of array: <class 'numpy.ndarray'>
shape of array: (9,)
size of array: 9


In [11]:
#Q2 numpy_ndarray
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.array([[1,1,1,1],
             [2,2,2,2],
             [3,3,3,3]])
X

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [18]:
#Q3 numpy_ndarray1
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2,33,2).reshape(4,4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [15]:
#Q4 pick_odd
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X % 2 != 0
print(Y)             
             

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
